spring.application.name=TheCasualWear
#
#Ket noi database
#
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ClothingShop
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
