spring.application.name=TheCasualWear

#SQL connect
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ClothingShop;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_batch_fetch_size=10
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#luu anh len cloudinary
cloudinary.cloud-name=dozzwbiww
cloudinary.api-key=355158441565431
cloudinary.api-secret=QvY_X8aX8KPRpN85KluizdfTK88

#Mail cho forgot password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhnhgth06559@gmail.com
spring.mail.password=uzwl ekjz lwbu engy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

#Vnpay
vnpay.tmn-code=SUBIH7ZN
vnpay.hash-secret=LKP2ZVFBAW4L7HFM1H3NALYNWQZ8QBVJ
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/order/vnpay-return

#Test bank
#Ngan hang: NCB
#So the: 9704198526191432198
#Ten chu the: NGUYEN VAN A
#Ngay phat hanh: 07/15
#OTP: 123456